<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.notifications' shared autowired service.

return $this->services['app.notifications'] = new \AppBundle\Service\NotificationService($this);
