<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.saml.service_provider_repository' shared autowired service.

return $this->services['app.saml.service_provider_repository'] = new \AppBundle\Repository\SamlServiceProviderRepository();
