<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\AdminBundle\Command\SetupAclCommand' shared service.

$this->services['Sonata\\AdminBundle\\Command\\SetupAclCommand'] = $instance = new \Sonata\AdminBundle\Command\SetupAclCommand(${($_ = isset($this->services['sonata.admin.pool']) ? $this->services['sonata.admin.pool'] : $this->getSonata_Admin_PoolService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.admin.manipulator.acl.admin']) ? $this->services['sonata.admin.manipulator.acl.admin'] : ($this->services['sonata.admin.manipulator.acl.admin'] = new \Sonata\AdminBundle\Util\AdminAclManipulator('Sonata\\AdminBundle\\Security\\Acl\\Permission\\MaskBuilder'))) && false ?: '_'});

$instance->setName('sonata:admin:setup-acl');

return $instance;
