<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.hivebrite' shared autowired service.

return $this->services['app.hivebrite'] = new \AppBundle\Service\HiveBriteService($this);
