<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\UserBundle\Action\LogoutAction' shared service.

return $this->services['Sonata\\UserBundle\\Action\\LogoutAction'] = new \Sonata\UserBundle\Action\LogoutAction();
