<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'twig.extension.sortbyfield' shared autowired service.

return $this->services['twig.extension.sortbyfield'] = new \Snilius\Twig\SortByFieldExtension();
