<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(['AppBundle\\Controller\\CommandController:generateInvoiceAction' => function () {
    return ${($_ = isset($this->services['service_locator.mctheb9']) ? $this->services['service_locator.mctheb9'] : $this->load('getServiceLocator_Mctheb9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PortalController:changeTierAction' => function () {
    return ${($_ = isset($this->services['service_locator.2po_rap']) ? $this->services['service_locator.2po_rap'] : $this->load('getServiceLocator_2poRapService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\CommandController::generateInvoiceAction' => function () {
    return ${($_ = isset($this->services['service_locator.mctheb9']) ? $this->services['service_locator.mctheb9'] : $this->load('getServiceLocator_Mctheb9Service.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\PortalController::changeTierAction' => function () {
    return ${($_ = isset($this->services['service_locator.2po_rap']) ? $this->services['service_locator.2po_rap'] : $this->load('getServiceLocator_2poRapService.php')) && false ?: '_'};
}]));
