<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\EasyExtendsBundle\Command\DumpMappingCommand' shared service.

return $this->services['Sonata\\EasyExtendsBundle\\Command\\DumpMappingCommand'] = new \Sonata\EasyExtendsBundle\Command\DumpMappingCommand();
