<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'expertcoder_swift_mailer.send_grid.transport' shared service.

$this->services['expertcoder_swift_mailer.send_grid.transport'] = $instance = new \ExpertCoder\Swiftmailer\SendGridBundle\Services\SendGridTransport('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', [], false);

$instance->setLogger(${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'});

return $instance;
