<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.appbundle_command_organisationtosourcedoggcommand' shared autowired service.

return $this->services['console.command.appbundle_command_organisationtosourcedoggcommand'] = new \AppBundle\Command\OrganisationToSourceDoggCommand();
