<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'httplug.async_client.default' shared service.

return $this->services['httplug.async_client.default'] = \Http\Discovery\HttpAsyncClientDiscovery::find();
