<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'monolog.logger.hivebrite' shared service.

$this->services['monolog.logger.hivebrite'] = $instance = new \Symfony\Bridge\Monolog\Logger('hivebrite');

$instance->pushHandler(${($_ = isset($this->services['monolog.handler.console']) ? $this->services['monolog.handler.console'] : $this->getMonolog_Handler_ConsoleService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.nested']) ? $this->services['monolog.handler.nested'] : $this->getMonolog_Handler_NestedService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.main']) ? $this->services['monolog.handler.main'] : $this->getMonolog_Handler_MainService()) && false ?: '_'});
$instance->pushHandler(${($_ = isset($this->services['monolog.handler.hivebrite']) ? $this->services['monolog.handler.hivebrite'] : $this->load('getMonolog_Handler_HivebriteService.php')) && false ?: '_'});

return $instance;
