<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.twig.extension.wrapping' shared service.

return $this->services['sonata.core.twig.extension.wrapping'] = new \Sonata\Twig\Extension\FormTypeExtension('standard');
