<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.route_loader' shared service.

return $this->services['sonata.admin.route_loader'] = new \Sonata\AdminBundle\Route\AdminPoolLoader(${($_ = isset($this->services['sonata.admin.pool']) ? $this->services['sonata.admin.pool'] : $this->load('getSonata_Admin_PoolService.php')) && false ?: '_'}, [0 => 'admin.companies', 1 => 'admin.company_addresses', 2 => 'admin.company_contacts', 3 => 'admin.company_documents', 4 => 'admin.documents_types', 5 => 'admin.company_directors', 6 => 'admin.company_shareholding', 7 => 'admin.company_types', 8 => 'admin.company_type_documentation', 9 => 'admin.company_references', 10 => 'admin.buyers', 11 => 'admin.buyer_membership', 12 => 'admin.members', 13 => 'admin.payments', 14 => 'admin.payment_modes', 15 => 'admin.promo_codes', 16 => 'admin.requests', 17 => 'admin.categories', 18 => 'admin.requests_type', 19 => 'admin.requests_documents', 20 => 'admin.company_requests', 21 => 'admin.news', 22 => 'admin.ujuzi_hub', 23 => 'admin.testimonials', 24 => 'admin.content_categories', 25 => 'admin.verification_stages', 26 => 'admin.verification_step', 27 => 'admin.company_verification', 28 => 'admin.staff', 29 => 'admin.user_guide.topic', 30 => 'admin.user_guide.content', 31 => 'admin.tiers', 32 => 'admin.tierBenefits', 33 => 'sonata.user.admin.user', 34 => 'sonata.user.admin.group'], $this);
