<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.twig.deprecated_template_extension' shared service.

return $this->services['sonata.core.twig.deprecated_template_extension'] = new \Sonata\Twig\Extension\DeprecatedTemplateExtension();
