<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.core.twig.template_extension' shared service.

return $this->services['sonata.core.twig.template_extension'] = new \Sonata\Twig\Extension\TemplateExtension(false, ${($_ = isset($this->services['translator.default']) ? $this->services['translator.default'] : $this->getTranslator_DefaultService()) && false ?: '_'}, ${($_ = isset($this->services['sonata.core.model.adapter.chain']) ? $this->services['sonata.core.model.adapter.chain'] : $this->load('getSonata_Core_Model_Adapter_ChainService.php')) && false ?: '_'});
