<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.block.loader.service' shared service.

return $this->services['sonata.block.loader.service'] = new \Sonata\BlockBundle\Block\Loader\ServiceLoader([0 => 'sonata.admin.block.admin_list', 1 => 'sonata.user.block.menu', 2 => 'sonata.user.block.account', 3 => 'sonata.block.service.text', 4 => 'sonata.block.dash', 'sonata.block.dash' => ['context' => []], 'sonata.block.service.container' => ['context' => []], 'sonata.block.service.empty' => ['context' => []], 'sonata.block.service.text' => ['context' => []], 'sonata.block.service.rss' => ['context' => []], 'sonata.block.service.menu' => ['context' => []], 'sonata.block.service.template' => ['context' => []], 'sonata.admin.block.admin_list' => ['context' => []], 'sonata.admin.block.search_result' => ['context' => []], 'sonata.admin.block.stats' => ['context' => []]]);
