<?php

namespace AppBundle\Repository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends \Doctrine\ORM\EntityRepository
{
  public function checkActiveSubscription($company)
  {
    $sql = 'SELECT s FROM AppBundle:CompanySubscription s WHERE s.company = :company ORDER BY s.id DESC';
    $q = $this->getEntityManager()->createQuery($sql)->setParameter('company',$company)->setMaxResults(1);
    return $q->getResult();
  }
}
