<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0ea6axc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0ea6axc/appProdProjectContainer.php') {
    touch(__DIR__.'/Container0ea6axc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container0ea6axc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container0ea6axc\appProdProjectContainer([
    'container.build_hash' => '0ea6axc',
    'container.build_id' => '4c5578f9',
    'container.build_time' => 1625432533,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0ea6axc');
