<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.print_service' shared autowired service.

return $this->services['app.print_service'] = new \AppBundle\Service\PrintService($this);
