<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.post.save' shared autowired service.

return $this->services['app.post.save'] = new \AppBundle\EventListener\PostSave($this);
