<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_user.group_manager' shared service.

return $this->services['fos_user.group_manager'] = new \Sonata\UserBundle\Entity\GroupManager(${($_ = isset($this->services['fos_user.object_manager']) ? $this->services['fos_user.object_manager'] : $this->load('getFosUser_ObjectManagerService.php')) && false ?: '_'}, 'Application\\Sonata\\UserBundle\\Entity\\Group');
