<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maker.auto_command.make_sonata_admin' shared service.

$this->services['maker.auto_command.make_sonata_admin'] = $instance = new \Symfony\Bundle\MakerBundle\Command\MakerCommand(new \Sonata\AdminBundle\Maker\AdminMaker($this->targetDirs[3], ['sonata.admin.manager.orm' => new \Sonata\DoctrineORMAdminBundle\Model\ModelManager(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'})]), ${($_ = isset($this->services['maker.file_manager']) ? $this->services['maker.file_manager'] : $this->load('getMaker_FileManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['maker.generator']) ? $this->services['maker.generator'] : $this->load('getMaker_GeneratorService.php')) && false ?: '_'});

$instance->setName('make:sonata:admin');

return $instance;
