<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CompanyDocumentation extends \AppBundle\Entity\CompanyDocumentation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'documentType', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'company', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'documentNumber', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'issuedBy', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'issueDate', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'expiryDate', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'verificationStatus'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'documentType', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'company', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'documentNumber', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'issuedBy', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'issueDate', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'expiryDate', '' . "\0" . 'AppBundle\\Entity\\CompanyDocumentation' . "\0" . 'verificationStatus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CompanyDocumentation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentType(\AppBundle\Entity\CompanyTypeDocumentation $documentType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentType', [$documentType]);

        return parent::setDocumentType($documentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentType', []);

        return parent::getDocumentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\AppBundle\Entity\Company $company = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentNumber($documentNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentNumber', [$documentNumber]);

        return parent::setDocumentNumber($documentNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentNumber', []);

        return parent::getDocumentNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssuedBy($issuedBy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssuedBy', [$issuedBy]);

        return parent::setIssuedBy($issuedBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssuedBy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssuedBy', []);

        return parent::getIssuedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setIssueDate($issueDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIssueDate', [$issueDate]);

        return parent::setIssueDate($issueDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getIssueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIssueDate', []);

        return parent::getIssueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiryDate($expiryDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiryDate', [$expiryDate]);

        return parent::setExpiryDate($expiryDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpiryDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpiryDate', []);

        return parent::getExpiryDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        return parent::setUpdatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerificationStatus($verificationStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerificationStatus', [$verificationStatus]);

        return parent::setVerificationStatus($verificationStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerificationStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerificationStatus', []);

        return parent::getVerificationStatus();
    }

}
