<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.sourcedogg' shared autowired service.

return $this->services['app.sourcedogg'] = new \AppBundle\Service\SourceDoggService($this);
