<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.crb_service' shared autowired service.

return $this->services['app.crb_service'] = new \AppBundle\Service\CRBService($this);
