<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Sonata\BlockBundle\Command\DebugBlocksCommand' shared service.

$this->services['Sonata\\BlockBundle\\Command\\DebugBlocksCommand'] = $instance = new \Sonata\BlockBundle\Command\DebugBlocksCommand(NULL, ${($_ = isset($this->services['sonata.block.manager']) ? $this->services['sonata.block.manager'] : $this->load('getSonata_Block_ManagerService.php')) && false ?: '_'});

$instance->setName('sonata:block:debug');

return $instance;
