<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.mctheb9' shared service.

return $this->services['service_locator.mctheb9'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['kernel' => function () {
    return ${($_ = isset($this->services['kernel']) ? $this->services['kernel'] : $this->get('kernel', 3)) && false ?: '_'};
}]);
