<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Sonata\UserBundle\Command\TwoStepVerificationCommand' shared service.

return $this->services['Sonata\\UserBundle\\Command\\TwoStepVerificationCommand'] = new \Sonata\UserBundle\Command\TwoStepVerificationCommand(NULL, NULL, ${($_ = isset($this->services['fos_user.user_manager']) ? $this->services['fos_user.user_manager'] : $this->load('getFosUser_UserManagerService.php')) && false ?: '_'});
