<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hwi_oauth.resource_owner.azure' shared service.

return $this->services['hwi_oauth.resource_owner.azure'] = new \HWI\Bundle\OAuthBundle\OAuth\ResourceOwner\AzureResourceOwner(${($_ = isset($this->services['hwi_oauth.http_client']) ? $this->services['hwi_oauth.http_client'] : $this->load('getHwiOauth_HttpClientService.php')) && false ?: '_'}, ${($_ = isset($this->services['security.http_utils']) ? $this->services['security.http_utils'] : $this->getSecurity_HttpUtilsService()) && false ?: '_'}, ['client_id' => '5e24a69b-f667-4c76-99d5-5d3ee52fb8df', 'client_secret' => '08tc7OZj9*a_dN--ORSc+h4IxDnMz/AG', 'options' => ['resource' => 'https://graph.microsoft.com', 'application' => '417f9f2c-0bb5-497d-bdb0-3c282099840f', 'csrf' => true, 'infos_url' => 'https://graph.microsoft.com/v1.0/me'], 'paths' => ['identifier' => 'email']], 'azure', new \HWI\Bundle\OAuthBundle\OAuth\RequestDataStorage\SessionStorage(${($_ = isset($this->services['session']) ? $this->services['session'] : $this->load('getSessionService.php')) && false ?: '_'}));
