<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\EventSubscriber\SamlSubscriber' shared autowired service.

return $this->services['AppBundle\\EventSubscriber\\SamlSubscriber'] = new \AppBundle\EventSubscriber\SamlSubscriber(${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())) && false ?: '_'});
