<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'services_resetter' shared service.

return $this->services['services_resetter'] = new \Symfony\Component\HttpKernel\DependencyInjection\ServicesResetter(new RewindableGenerator(function () {
    if (isset($this->services['cache.app'])) {
        yield 'cache.app' => ${($_ = isset($this->services['cache.app']) ? $this->services['cache.app'] : null) && false ?: '_'};
    }
    if (isset($this->services['cache.system'])) {
        yield 'cache.system' => ${($_ = isset($this->services['cache.system']) ? $this->services['cache.system'] : null) && false ?: '_'};
    }
    if (isset($this->services['cache.validator'])) {
        yield 'cache.validator' => ${($_ = isset($this->services['cache.validator']) ? $this->services['cache.validator'] : null) && false ?: '_'};
    }
    if (isset($this->services['cache.serializer'])) {
        yield 'cache.serializer' => ${($_ = isset($this->services['cache.serializer']) ? $this->services['cache.serializer'] : null) && false ?: '_'};
    }
    if (isset($this->services['cache.annotations'])) {
        yield 'cache.annotations' => ${($_ = isset($this->services['cache.annotations']) ? $this->services['cache.annotations'] : null) && false ?: '_'};
    }
    if (isset($this->services['profiler'])) {
        yield 'profiler' => ${($_ = isset($this->services['profiler']) ? $this->services['profiler'] : null) && false ?: '_'};
    }
    if (isset($this->services['validator'])) {
        yield 'debug.validator' => ${($_ = isset($this->services['validator']) ? $this->services['validator'] : null) && false ?: '_'};
    }
    if (isset($this->services['debug.stopwatch'])) {
        yield 'debug.stopwatch' => ${($_ = isset($this->services['debug.stopwatch']) ? $this->services['debug.stopwatch'] : null) && false ?: '_'};
    }
    if (isset($this->services['debug.event_dispatcher'])) {
        yield 'debug.event_dispatcher' => ${($_ = isset($this->services['debug.event_dispatcher']) ? $this->services['debug.event_dispatcher'] : null) && false ?: '_'};
    }
    if (isset($this->services['security.token_storage'])) {
        yield 'security.token_storage' => ${($_ = isset($this->services['security.token_storage']) ? $this->services['security.token_storage'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.import'])) {
        yield 'monolog.handler.import' => ${($_ = isset($this->services['monolog.handler.import']) ? $this->services['monolog.handler.import'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.hivebrite'])) {
        yield 'monolog.handler.hivebrite' => ${($_ = isset($this->services['monolog.handler.hivebrite']) ? $this->services['monolog.handler.hivebrite'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.sms'])) {
        yield 'monolog.handler.sms' => ${($_ = isset($this->services['monolog.handler.sms']) ? $this->services['monolog.handler.sms'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.email'])) {
        yield 'monolog.handler.email' => ${($_ = isset($this->services['monolog.handler.email']) ? $this->services['monolog.handler.email'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.hubtel'])) {
        yield 'monolog.handler.hubtel' => ${($_ = isset($this->services['monolog.handler.hubtel']) ? $this->services['monolog.handler.hubtel'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.azure'])) {
        yield 'monolog.handler.azure' => ${($_ = isset($this->services['monolog.handler.azure']) ? $this->services['monolog.handler.azure'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.dumps'])) {
        yield 'monolog.handler.dumps' => ${($_ = isset($this->services['monolog.handler.dumps']) ? $this->services['monolog.handler.dumps'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.main'])) {
        yield 'monolog.handler.main' => ${($_ = isset($this->services['monolog.handler.main']) ? $this->services['monolog.handler.main'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.console'])) {
        yield 'monolog.handler.console' => ${($_ = isset($this->services['monolog.handler.console']) ? $this->services['monolog.handler.console'] : null) && false ?: '_'};
    }
    if (isset($this->services['monolog.handler.server_log'])) {
        yield 'monolog.handler.server_log' => ${($_ = isset($this->services['monolog.handler.server_log']) ? $this->services['monolog.handler.server_log'] : null) && false ?: '_'};
    }
    if (isset($this->services['swiftmailer.email_sender.listener'])) {
        yield 'swiftmailer.email_sender.listener' => ${($_ = isset($this->services['swiftmailer.email_sender.listener']) ? $this->services['swiftmailer.email_sender.listener'] : null) && false ?: '_'};
    }
    if (isset($this->services['form.type.entity'])) {
        yield 'form.type.entity' => ${($_ = isset($this->services['form.type.entity']) ? $this->services['form.type.entity'] : null) && false ?: '_'};
    }
}, function () {
    return 0 + (int) (isset($this->services['cache.app'])) + (int) (isset($this->services['cache.system'])) + (int) (isset($this->services['cache.validator'])) + (int) (isset($this->services['cache.serializer'])) + (int) (isset($this->services['cache.annotations'])) + (int) (isset($this->services['profiler'])) + (int) (isset($this->services['validator'])) + (int) (isset($this->services['debug.stopwatch'])) + (int) (isset($this->services['debug.event_dispatcher'])) + (int) (isset($this->services['security.token_storage'])) + (int) (isset($this->services['monolog.handler.import'])) + (int) (isset($this->services['monolog.handler.hivebrite'])) + (int) (isset($this->services['monolog.handler.sms'])) + (int) (isset($this->services['monolog.handler.email'])) + (int) (isset($this->services['monolog.handler.hubtel'])) + (int) (isset($this->services['monolog.handler.azure'])) + (int) (isset($this->services['monolog.handler.dumps'])) + (int) (isset($this->services['monolog.handler.main'])) + (int) (isset($this->services['monolog.handler.console'])) + (int) (isset($this->services['monolog.handler.server_log'])) + (int) (isset($this->services['swiftmailer.email_sender.listener'])) + (int) (isset($this->services['form.type.entity']));
}), ['cache.app' => 'reset', 'cache.system' => 'reset', 'cache.validator' => 'reset', 'cache.serializer' => 'reset', 'cache.annotations' => 'reset', 'profiler' => 'reset', 'debug.validator' => 'reset', 'debug.stopwatch' => 'reset', 'debug.event_dispatcher' => 'reset', 'security.token_storage' => 'setToken', 'monolog.handler.import' => 'reset', 'monolog.handler.hivebrite' => 'reset', 'monolog.handler.sms' => 'reset', 'monolog.handler.email' => 'reset', 'monolog.handler.hubtel' => 'reset', 'monolog.handler.azure' => 'reset', 'monolog.handler.dumps' => 'reset', 'monolog.handler.main' => 'reset', 'monolog.handler.console' => 'reset', 'monolog.handler.server_log' => 'reset', 'swiftmailer.email_sender.listener' => 'reset', 'form.type.entity' => 'reset']);
