<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.block.manager' shared service.

$this->services['sonata.block.manager'] = $instance = new \Sonata\BlockBundle\Block\BlockServiceManager($this, false, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->load('getLoggerService.php')) && false ?: '_'});

$instance->add('sonata.block.dash', 'sonata.block.dash', [0 => 'cms']);
$instance->add('sonata.block.service.container', 'sonata.block.service.container', []);
$instance->add('sonata.block.service.empty', 'sonata.block.service.empty', []);
$instance->add('sonata.block.service.text', 'sonata.block.service.text', [0 => 'cms']);
$instance->add('sonata.block.service.rss', 'sonata.block.service.rss', []);
$instance->add('sonata.block.service.menu', 'sonata.block.service.menu', []);
$instance->add('sonata.block.service.template', 'sonata.block.service.template', []);
$instance->add('sonata.admin.block.admin_list', 'sonata.admin.block.admin_list', [0 => 'admin']);
$instance->add('sonata.admin.block.search_result', 'sonata.admin.block.search_result', []);
$instance->add('sonata.admin.block.stats', 'sonata.admin.block.stats', []);

return $instance;
