AppBundle\Entity\Category:
  type: entity
  table:  categories
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
    slug:
      type: string
      length: 300
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
      nullable: true
  manyToOne:
    parent:
      targetEntity: Category
      inversedBy: children
      joinColumn:
        parent_id:
          referencedColumnName: id
  oneToMany:
    children:
      targetEntity: Category
      mappedBy: parent
  manyToMany:
    companies:
      targetEntity: Company
      mappedBy: categories
    requests:
      targetEntity: Request
      mappedBy: tags
  lifecycleCallbacks:
    prePersist: ['setSlugValue','setCreatedAtValue']
    preUpdate: ['setSlugValue','setUpdateAtValue']
