AppBundle\Entity\CompanyContact:
  type: entity
  table:  company_contacts
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 255
      nullable: true
    designation:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    mobile:
      type: string
      length: 255
      nullable: true
    contactAddress:
      type: string
      length: 255
      nullable: true
    phone:
      type: string
      length: 255
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
      nullable: true
  manyToOne:
    company:
      targetEntity: Company
      inversedBy: contacts
      onDelete: CASCADE
      joinColumn:
        company_id:
          referencedColumnName: id
        onDelete: CASCADE
  lifecycleCallbacks:
    prePersist: [setCreatedAtValue]
    preUpdate: [setUpdatedAtValue]
