AppBundle\Entity\CompanyVerification:
  type: entity
  table:  company_verification
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    status:
      type: string
      length: 14
      nullable: true
      options:
        default:  'Not Done'
    approvalStatus:
      type: string
      length: 14
      nullable: true
    remarks:
      type: string
      length: 10000
      nullable: true
    verificationDate:
      type: datetime
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
      nullable: true
  manyToOne:
    company:
      targetEntity: Company
      inversedBy: verification
      joinColumn:
        company_id:
          referencedColumnName: id
        onDelete: CASCADE
    verificationStep:
      targetEntity: VerificationStep
      inversedBy: verification
      joinColumn:
        verification_id:
          referencedColumnName: id
        onDelete: CASCADE
    verifiedBy:
      targetEntity: Staff
      inversedBy: null
      joinColumn:
        staff_id:
          referencedColumnName: id
  lifecycleCallbacks:
      prePersist: [setCreatedAtValue]
      preUpdate: [setUpdatedAtValue]
