AppBundle\Entity\DocumentType:
  type: entity
  table:  document_types
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
