AppBundle\Entity\PaymentMode:
  type: entity
  table:  payment_modes
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 50
    description:
      type: string
      length: 255
      nullable: true
    instructions:
      type: text
  oneToMany:
    payments:
      targetEntity: Payment
      mappedBy: mode
