AppBundle\Entity\Province:
  type: entity
  table:  provinces
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
  manyToMany:
    companies:
      targetEntity: Company
      mappedBy: provinces
