AppBundle\Entity\SourceDoggSSO:
  type: entity
  table:  sourcedogg_sso
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    dhot:
      type: string
      length: 255
    cookie:
      type: string
      length: 255
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
      nullable: true
  oneToOne:
    member:
      targetEntity: Member
      inversedBy: sdsso
      joinColumn:
        member_id:
          referencedColumnName: id
        onDelete: CASCADE
  lifecycleCallbacks:
    prePersist: [setCreatedAtValue]
    preUpdate: [setUpdatedAtValue]
