AppBundle\Entity\TierBenefit:
  type: entity
  table:  tier_benefits
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 255
  manyToOne:
    tier:
      targetEntity: Tier
      inversedBy: benefits
      joinColumn:
        tier_id:
          referencedColumnName: id
        onDelete: CASCADE
