AppBundle\Entity\VerificationStage:
  type: entity
  table:  verification_stages
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 100
    description:
      type: string
      length: 10000
  oneToMany:
    steps:
      targetEntity: VerificationStep
      cascade:  [persist]
      orphanRemoval:  true
      mappedBy: stage
