<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sonata.easy_extends.doctrine.mapper' shared service.

$this->services['sonata.easy_extends.doctrine.mapper'] = $instance = new \Sonata\EasyExtendsBundle\Mapper\DoctrineORMMapper(${($_ = isset($this->services['doctrine']) ? $this->services['doctrine'] : $this->getDoctrineService()) && false ?: '_'}, []);

$instance->addAssociation('Application\\Sonata\\UserBundle\\Entity\\User', 'mapManyToMany', [0 => ['fieldName' => 'groups', 'targetEntity' => 'Application\\Sonata\\UserBundle\\Entity\\Group', 'cascade' => [], 'joinTable' => ['name' => 'fos_user_user_group', 'joinColumns' => [0 => ['name' => 'user_id', 'referencedColumnName' => 'id', 'onDelete' => 'CASCADE']], 'inverseJoinColumns' => [0 => ['name' => 'group_id', 'referencedColumnName' => 'id', 'onDelete' => 'CASCADE']]]]]);

return $instance;
