<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.request_matcher.kenuv22' shared service.

return $this->services['security.request_matcher.kenuv22'] = new \Symfony\Component\HttpFoundation\RequestMatcher('^/oauth/v2/auth');
