<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1drl5ev\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1drl5ev/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1drl5ev.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1drl5ev\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container1drl5ev\appDevDebugProjectContainer([
    'container.build_hash' => '1drl5ev',
    'container.build_id' => '1a1b43b5',
    'container.build_time' => 1583748481,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1drl5ev');
