<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRzhy63s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRzhy63s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRzhy63s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRzhy63s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRzhy63s\appDevDebugProjectContainer([
    'container.build_hash' => 'Rzhy63s',
    'container.build_id' => '77d0f066',
    'container.build_time' => 1624539424,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRzhy63s');
