<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BusinessGrowthHub extends \AppBundle\Entity\BusinessGrowthHub implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'summary', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'contentType', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'content', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'author', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'isPublished', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'filename', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'clicks', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'externalLink', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'isPremiumContent', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'buyer'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'title', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'summary', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'contentType', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'content', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'author', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'isPublished', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'filename', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'clicks', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'externalLink', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'isPremiumContent', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'slug', '' . "\0" . 'AppBundle\\Entity\\BusinessGrowthHub' . "\0" . 'buyer'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (BusinessGrowthHub $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSummary($summary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSummary', [$summary]);

        return parent::setSummary($summary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSummary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummary', []);

        return parent::getSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function setContentType($contentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContentType', [$contentType]);

        return parent::setContentType($contentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getContentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContentType', []);

        return parent::getContentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setContent($content)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContent', [$content]);

        return parent::setContent($content);
    }

    /**
     * {@inheritDoc}
     */
    public function getContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContent', []);

        return parent::getContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAuthor($author)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAuthor', [$author]);

        return parent::setAuthor($author);
    }

    /**
     * {@inheritDoc}
     */
    public function getAuthor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAuthor', []);

        return parent::getAuthor();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPublished($isPublished)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPublished', [$isPublished]);

        return parent::setIsPublished($isPublished);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPublished()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPublished', []);

        return parent::getIsPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setFilename($filename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFilename', [$filename]);

        return parent::setFilename($filename);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilename', []);

        return parent::getFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setClicks($clicks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClicks', [$clicks]);

        return parent::setClicks($clicks);
    }

    /**
     * {@inheritDoc}
     */
    public function getClicks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClicks', []);

        return parent::getClicks();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalLink($externalLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalLink', [$externalLink]);

        return parent::setExternalLink($externalLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalLink', []);

        return parent::getExternalLink();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\AppBundle\Entity\ContentCategory $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', [$category]);

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategory(\AppBundle\Entity\ContentCategory $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategory', [$category]);

        return parent::removeCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', []);

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function lifecycleFileUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'lifecycleFileUpload', []);

        return parent::lifecycleFileUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function refreshUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'refreshUpdated', []);

        return parent::refreshUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function updateSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateSlug', []);

        return parent::updateSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPremiumContent($isPremiumContent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPremiumContent', [$isPremiumContent]);

        return parent::setIsPremiumContent($isPremiumContent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsPremiumContent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsPremiumContent', []);

        return parent::getIsPremiumContent();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyer(\AppBundle\Entity\Buyer $buyer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyer', [$buyer]);

        return parent::setBuyer($buyer);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyer', []);

        return parent::getBuyer();
    }

}
