<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CompanyRequest extends \AppBundle\Entity\CompanyRequest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'invitationDate', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'responseDate', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'buyerRemarks', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'supplierRemarks', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'documents', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'request', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'company', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'score'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'invitationDate', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'responseDate', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'buyerRemarks', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'supplierRemarks', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'createdAt', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'updatedAt', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'documents', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'request', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'company', '' . "\0" . 'AppBundle\\Entity\\CompanyRequest' . "\0" . 'score'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CompanyRequest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvitationDate($invitationDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvitationDate', [$invitationDate]);

        return parent::setInvitationDate($invitationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvitationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvitationDate', []);

        return parent::getInvitationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponseDate($responseDate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponseDate', [$responseDate]);

        return parent::setResponseDate($responseDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponseDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponseDate', []);

        return parent::getResponseDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyerRemarks($buyerRemarks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyerRemarks', [$buyerRemarks]);

        return parent::setBuyerRemarks($buyerRemarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyerRemarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyerRemarks', []);

        return parent::getBuyerRemarks();
    }

    /**
     * {@inheritDoc}
     */
    public function setSupplierRemarks($supplierRemarks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSupplierRemarks', [$supplierRemarks]);

        return parent::setSupplierRemarks($supplierRemarks);
    }

    /**
     * {@inheritDoc}
     */
    public function getSupplierRemarks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSupplierRemarks', []);

        return parent::getSupplierRemarks();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\AppBundle\Entity\CompanyRequestDocument $document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', [$document]);

        return parent::addDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\AppBundle\Entity\CompanyRequestDocument $document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', [$document]);

        return parent::removeDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequest(\AppBundle\Entity\Request $request = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequest', [$request]);

        return parent::setRequest($request);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequest()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequest', []);

        return parent::getRequest();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\AppBundle\Entity\Company $company = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAtValue', []);

        return parent::setUpdatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setScore($score = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScore', [$score]);

        return parent::setScore($score);
    }

    /**
     * {@inheritDoc}
     */
    public function getScore()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScore', []);

        return parent::getScore();
    }

}
